var _datosIniciales = {
  "empleados": [
    {"id":"dui-010748799","nombre":"ESCALANTE GUERRERO, JOSE MARCIAL","dui":"01074879-9","telefono":"","direccion":"SANTA ANA, SANTA ANA CENTRO, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-002029547","nombre":"CRUZ VALLE, MARIO ANTONIO","dui":"00202954-7","telefono":"","direccion":"COMUNIDAD LA REALIDAD EL PPAL LOTE #536, CUTUMAY CAMONES, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-037183562","nombre":"MORALES GUZMAN, GUSTAVO ALEXANDER","dui":"03718356-2","telefono":"","direccion":"COL LAS GRANADILLAS LOTE #206 CTON ZACARIAS, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-037520900","nombre":"FLORES CACERES, HECTOR DANIEL","dui":"03752090-0","telefono":"","direccion":"COL JARDINES DE SANTA ANITA POLG 17 PJE SONSONATE CASA #13, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-045135086","nombre":"PALACIOS AREVALO, JUAN ALBERTO","dui":"04513508-6","telefono":"","direccion":"COL LA REALIDAD CL LAS HUERTAS LOTE #19, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-029122992","nombre":"PEREZ BRENES, JULIO ARMANDO","dui":"02912299-2","telefono":"","direccion":"COL EL MILAGRO POL 8 CALLE A METAPAN #5, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-001520142","nombre":"MORENO MEDINA, MELVIN DE JESUS","dui":"00152014-2","telefono":"","direccion":"COL LA DALIA PJE EL MILAGRO LOTE 26, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-031447772","nombre":"MENDOZA, ISMAEL DE JESUS","dui":"03144777-2","telefono":"","direccion":"LOT JARDINES DE SANTA ANITA PJE SONSONATE, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-010671138","nombre":"CEA SALGUERO, REIMUNDO","dui":"01067113-8","telefono":"","direccion":"LOT TERESITA #5 CANTARRANA, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-062383896","nombre":"ULLOA MENDEZ, JOSE ANGEL","dui":"06238389-6","telefono":"","direccion":"COL LAS GRANADILLAS CASA #3, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-031982730","nombre":"MUSON VALENCIA, SAMUEL HUMBERTO","dui":"03198273-0","telefono":"","direccion":"COL OLIMPICA CALLE CENTRAL POL B CASA 29 EL PORTEZUELO, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-063588960","nombre":"MARTINEZ MARTINEZ, TOMAS ALEJANDRO","dui":"06358896-0","telefono":"","direccion":"SANTA ANA, SANTA ANA CENTRO, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-007667120","nombre":"PACHECO CEA, JOSE ERNESTO","dui":"00766712-0","telefono":"","direccion":"COL LA REALIDAD SECTOR 6 CASA 40, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-026729494","nombre":"GUDIEL, ROBERTO ERNESTO","dui":"02672949-4","telefono":"","direccion":"COL LA ESMERALDA FINAL 6A AV NTE APTO RAMOS, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-042631596","nombre":"GONZALEZ ALARCON, JERSON YONATAN","dui":"04263159-6","telefono":"","direccion":"COL LA ESMERALDA FINAL 6 AV NTE CASA #2, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-046461171","nombre":"GONZALEZ MARTINEZ, JOSE RICARDO","dui":"04646117-1","telefono":"","direccion":"COL SANTA EDUVIGES AV LOS AMATES, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-063292103","nombre":"RAMOS ESCOBAR, JOSUE ALFONSO","dui":"06329210-3","telefono":"","direccion":"CHALCHUAPA, SANTA ANA OESTE, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-046673338","nombre":"MARTINEZ DE OSORIO, JOSELINE DEL ROCIO","dui":"04667333-8","telefono":"","direccion":"COL LA DALIA CL DIAGONAL BLOCK \"A\" N 6, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-026260903","nombre":"BERRIOS PINTO, MARIA MAGDALENA","dui":"02626090-3","telefono":"","direccion":"SANTA ANA, SANTA ANA CENTRO, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-007056620","nombre":"MARTINEZ, JOSE LUIS","dui":"00705662-0","telefono":"","direccion":"COL EL BUFALO FINAL 5 AV NTE MESON LA ROCA, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""},
    {"id":"dui-023911149","nombre":"FLORES ROMERO, EMILIA LIZETH","dui":"02391114-9","telefono":"","direccion":"SANTA ANA, SANTA ANA","fechaIngreso":"2026-01-01","cargo":"Operario","departamento":"Trabajos varios","salarioHora":1.68,"tipoPago":"Semanal","afpInstitucion":"ConfÃ­a","contactoNombre":"","contactoTelefono":"","contactoParentesco":"","estado":"activo","fechaSalida":""}
  ],
  "planillas": [],
  "historialPagos": [],
  "boletas": []
}; /* __DATOS_INICIALES__ */
